#!/bin/sh

if [ "$(id -un)" != "$PAM_USER" ]; then
    su "$PAM_USER" -s "$0" "$@"
else
    read -r PAM_PASS
    PAM_PASS=$(echo "$PAM_PASS" | sed 's/\$/\\\$/')

    SSH_AUTH_SOCK=/run/user/$(id -u "$PAM_USER")/ssh-agent.socket
    export SSH_AUTH_SOCK

    if [ -d /home/"$PAM_USER"/.ssh/unlock.d/ ]; then
        find /home/"$PAM_USER"/.ssh/unlock.d/ -maxdepth 1 ! -wholename "/home/$PAM_USER/.ssh/unlock.d/" ! -name "config" ! -name "known_hosts" ! -name "*.pub" | while read -r key; do

            printf '
            log_user 1

            spawn ssh-add "%s"

            expect "Enter passphrase for %s" {
                send "%s\r"
            }

            expect eof
            ' "$key" "$key" "$PAM_PASS" | expect &
        done
    fi
fi

exit 0
