#!/bin/sh

if [ "$(id -un)" != "$PAM_USER" ]; then
    su "$PAM_USER" -s "$0" "$@"
else
    if [ -d "/home/$PAM_USER/.ssh/unlock.d" ]; then
        unlockdir="/home/$PAM_USER/.ssh/unlock.d"
    fi

    if [ -d "/home/$PAM_USER/.ssh/pam.d" ]; then
        unlockdir="/home/$PAM_USER/.ssh/pam.d"
    fi

    if [ -d "/home/$PAM_USER/.config/ssh/unlock.d" ]; then
        unlockdir="/home/$PAM_USER/.config/ssh/unlock.d"
    fi

    if [ -d "/home/$PAM_USER/.config/ssh/pam.d" ]; then
        unlockdir="/home/$PAM_USER/.config/ssh/pam.d"
    fi


    if [ -n "$unlockdir" ]; then
        read -r PAM_PASS
        PAM_PASS=$(echo "$PAM_PASS" | sed 's/\$/\\\$/')

        if hash keychain 2>/dev/null; then
                eval "$(keychain --eval --quiet)"
        else
                SSH_AUTH_SOCK=/run/user/$(id -u "$PAM_USER")/ssh-agent.socket
                export SSH_AUTH_SOCK
        fi

        find "$unlockdir" -maxdepth 1 ! -wholename "$unlockdir" | while read -r key; do
            printf 'log_user 1\n\nspawn ssh-add "%s"\n\nexpect "Enter passphrase for %s" {\nsend "%s\r"\n}\n\nexpect eof' "$key" "$key" "$PAM_PASS" | expect
        done
    fi
fi

exit 0
